micronaut:
  application:
    name: bookStore
cassandra:
  default:
    advanced:
      metadata:
        schema:
          enabled: false
    basic:
      contact-points:
        - "127.0.0.1:9042"
        - "127.0.0.2:8042"
      load-balancing-policy:
        local-datacenter: datacenter1

## Nats
nats:
  enabled: false
  addresses: ${nats_host:localhost}
  username: ${nats_username:guest}
  password: ${nats_password:guest}
